DROP TABLE IF EXISTS bonus_cards;
DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;

CREATE TABLE bonus_cards
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount BIGINT NOT NULL DEFAULT 0,
    ovner  VARCHAR(50)
);

CREATE TABLE operations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bonus_card_id BIGINT,
    amount_change BIGINT
);

CREATE TABLE users
(
    username VARCHAR(50)  NOT NULL PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE authorities
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);